Merge develop into main
DataSQRL/sqrl pull request #360
Opened 2023-10-08 23:14 UTC by henneberger

2023-10-10 17:04 UTC, mbroecheler requested changes
Looking good. The simplification around SQRLTable is very noticable. Good work!

2023-10-10 17:10 UTC, henneberger commented on sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/QueryPlanner.java
> +  private final AtomicInteger uniquePkId = new AtomicInteger(0);
It alleviates the need to keep track of the table alias when adding columns to the select/group/order clause.

2023-10-10 17:14 UTC, henneberger commented on sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/flink/FlinkDebugPhysicalIT/debugC3602OutputSelectTablesTest.txt
> +1332, 8, 1, 2023-05-19 02:28:39.553
we moved off h2 completely for tests

2023-10-10 17:17 UTC, henneberger commented on sqrl-engines/sqrl-engine-core/src/main/java/com/datasqrl/plan/hints/TimestampHint.java
> +public class TimestampHint implements SqrlHint {
Only adding the hint was scoped in the sprint

2023-10-10 17:29 UTC, henneberger commented on sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/QueryPlanner.java
> +    if (dialect == Dialect.POSTGRES) {
good catch

2023-10-10 17:34 UTC, henneberger commented on sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/SqrlFramework.java
> +  private Map<Name,AtomicInteger> tableNameShadowing = new HashMap<Name,AtomicInteger>();
not used, I'll clean up all unique counters

2023-10-10 17:36 UTC, henneberger commented on sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/schema/ScriptPlanner.java
> +    String columnName;
One is final display name, the other is a globally unique name b/c there is no guarantee there is a table alias on the table macro

2023-10-10 17:51 UTC, mbroecheler commented on sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/flink/FlinkDebugPhysicalIT/debugC3602OutputSelectTablesTest.txt
> +1332, 8, 1, 2023-05-19 02:28:39.553
Ah, I didn't realize that. Does Postgres not support timezones? Is this an issue we need to address?

2023-10-10 18:01 UTC, henneberger commented on sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/flink/FlinkDebugPhysicalIT/debugC3602OutputSelectTablesTest.txt
> +1332, 8, 1, 2023-05-19 02:28:39.553
It is a `timestamp with time zone` type. From the postgres docs:

For timestamp with time zone, the internally stored value is always in UTC (Universal Coordinated Time, traditionally known as Greenwich Mean Time, GMT). An input value that has an explicit time zone specified is converted to UTC using the appropriate offset for that time zone. If no time zone is stated in the input string, then it is assumed to be in the time zone indicated by the system's [TimeZone](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-TIMEZONE) parameter, and is converted to UTC using the offset for the timezone zone.

2023-10-12 19:13 UTC, mbroecheler approved these changes

2023-10-13 22:47 UTC, merged