Validate package subsection in package.json
DataSQRL/sqrl pull request #597
Opened 2024-05-10 14:34 UTC by nandorsoma

This PR introduces validation for config files, with initial focus on validating packages being uploaded to the repository. The ultimate goal is to make it extendable for the validation of the entire Sqrl config, hence its placement within _SqrlConfigCommons_. Here are some considerations driving the current design:

- **Individual vs. combined configurations:** We can validate either individual configurations or the resultant `CombinedConfiguration`. While the `CombinedConfiguration` is critical for us, providing validation feedback on individual files may be more beneficial to the user. Hence, every file is validated separately.
  
- **Precedence in configurations:** Given that if a section is present across multiple files, one of them takes precedence over the others, we need to consider if this is valid for the "package" section. Should there be only one "package" section? If so, we may require a "strict" combination rule which doesn't allow overrides for certain use-cases. This requires further thoughts and feedback.
  
- **Validation point:** Validation could be performed either before parsing the file into `Configuration` (validating raw user input) or after (validating `Configuration` object). The latter avoids duplicate file reads from the disk and has been implemented for now.
  
- **Configuration to JsonObject:** The conversion of `Configuration` to `JsonObject` required a custom converter. An alternate approach would utilize `SqrlConfigCommons.toMap` and pass the result to the `JsonObject` constructor, necessitating minor modifications to the `toMap` method. This alternate approach was not chosen to avoid touch-points with `getKeys` and `getAllKeys`, and to retain code readability despite the minor duplication in function.

I look forward to further discussions on these points, particularly on the potential implementation of a "strict" combination rule and the preferred approach for converting `Configuration` to `JsonObject`.

2024-05-10 14:50 UTC, nandorsoma commented on sqrl-tools/sqrl-config/src/main/resources/schema/package-schema.json
> +          "pattern": "^(\\d+\\.\\d+\\.\\d+)$"
Do we want to enforce a pattern in versioning or is it enough if it is a string?

2024-05-15 21:03 UTC, mbroecheler requested changes
Did a quick cursory review. Not sure if this PR is still relevant but thought the comments might help to understand the context.

2024-05-15 21:03 UTC, mbroecheler commented on sqrl-tools/sqrl-config/src/main/java/com/datasqrl/config/SqrlConfigCommons.java
> +  private static boolean isValid(Configuration baseconfig) {
SqrlConfigCommons is a general configuration class that we use to read all kinds of configuration files. The logic for validating that a file has a particular schema needs to live in a separate class to not mix concerns.

2024-05-15 21:03 UTC, mbroecheler commented on sqrl-tools/sqrl-config/src/main/resources/schema/package-schema.json
> +  "additionalProperties": false
The package.json file is used to configure the datasqrl compiler. It contains lots of other configuration options.
I'm surprised that this does not break the compiler. Are you not getting test failures with this?

2024-08-29 02:56 UTC, henneberger commented
closing due to staleness. we can readdress later since it is still needed

2024-08-29 02:56 UTC, closed without merging