Moving logic with a graph to a separate library in NPM.
DataSQRL/sqrl pull request #939
Opened 2024-10-22 02:11 UTC by ustymenkopavlodevima

The page has been moved to a separate library and rewritten in TypeScript for ease of further development and support, as it is used in both the sqrl repository and the client-frontend repository.

Source code repository - https://github.com/DataSQRL/dag-visualization/
NPM package page - https://www.npmjs.com/package/@datasqrl/dag-visualization
Compiled code - https://www.unpkg.com/browse/@datasqrl/dag-visualization@latest/

2024-11-01 20:05 UTC, mbroecheler requested changes
Two minor comments

2024-11-01 20:05 UTC, mbroecheler commented on sqrl-tools/sqrl-packager/src/main/resources/visualize_dag.html
> +      const edges = elements.flatMap((node) =>
Can we move the transformation from elements to nodes and edges into the renderGraph method?

2024-11-01 20:05 UTC, mbroecheler commented on sqrl-tools/sqrl-packager/src/main/resources/visualize_dag.html
>      <title>Visualize DAG with Cytoscape.js</title>
Could you please rename this to "DataSQRL Deployment Graph Visualization"

2024-11-08 23:12 UTC, mbroecheler commented
This looks good. This PR is ready to be merged once we have made the changes I slacked you in the visualization library. Let's keep this open until then.

2025-04-22 20:12 UTC, velo approved these changes

2025-04-29 19:39 UTC, mbroecheler approved these changes

2025-04-29 20:12 UTC, merged